### ISSUE TITLE
Crash panic: interface conversion: interface {} is []interface {}, not string

### ISSUE THREAD

**Issue by coffmant** [F5Networks/terraform-provider-bigip#470]
### Environment

 * TMOS/Bigip Version: 13.1.3.6 Build 0.0.4 Point Release 6
 * Terraform Version: 0.13.6
 * Terraform bigip provider Version: 1.8.0

### Summary

Terraform crashes during plan after an update from 1.7.0 to 1.8.0

### Steps To Reproduce

1. terraform plan results in a crash.  Critical section of the crash log is below.

2021/04/08 09:21:33 [TRACE] GRPCProvider: UpgradeResourceState
2021-04-08T09:21:33.455-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0: panic: interface conversion: interface {} is []interface {}, not string
2021-04-08T09:21:33.455-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0:
2021-04-08T09:21:33.455-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0: goroutine 407 [running]:
2021-04-08T09:21:33.456-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0: github.com/F5Networks/terraform-provider-bigip/bigip.resourceBigipLtmProfileClientSSLRead(0xc0003ffd50, 0x10f9d40, 0xc0000eee00, 0
xc0003ffd50, 0x0)
2021-04-08T09:21:33.456-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0:    github.com/F5Networks/terraform-provider-bigip/bigip/resource_bigip_ltm_profile_ssl_client.go:757 +0x8190
2021-04-08T09:21:33.456-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000119d00, 0xc0004a1810, 0x10f9d40, 0xc0000eee00, 0xc00000e538, 0x0, 0x0)
2021-04-08T09:21:33.456-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0:    github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/resource.go:455 +0x129
2021-04-08T09:21:33.456-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0000aab90, 0x1299060, 0xc0002023c0, 0xc0004a1720, 0xc0000aab90, 0xc0002023c0, 0xc0002d9a48)
2021-04-08T09:21:33.456-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0:    github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/helper/plugin/grpc_provider.go:525 +0x3dd
2021-04-08T09:21:33.456-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x10bb780, 0xc0000aab90, 0x1299060, 0xc0002023c0, 0xc0002ede00, 0x0, 0x1299060, 0xc0002023c0, 0xc000538000, 0x57a)
2021-04-08T09:21:33.456-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0:    github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/tfplugin5/tfplugin5.pb.go:3153 +0x214
2021-04-08T09:21:33.456-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000d4000, 0x12a2fe0, 0xc0000afb00, 0xc0003a7b00, 0xc0004866c0, 0x186bf30, 0x0, 0x0, 0x0)
2021-04-08T09:21:33.456-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0:    google.golang.org/grpc@v1.23.0/server.go:995 +0x482
2021-04-08T09:21:33.456-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0: google.golang.org/grpc.(*Server).handleStream(0xc0000d4000, 0x12a2fe0, 0xc0000afb00, 0xc0003a7b00, 0x0)
2021-04-08T09:21:33.456-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0:    google.golang.org/grpc@v1.23.0/server.go:1275 +0xd34
2021-04-08T09:21:33.456-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000381e0, 0xc0000d4000, 0x12a2fe0, 0xc0000afb00, 0xc0003a7b00)
2021-04-08T09:21:33.456-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0:    google.golang.org/grpc@v1.23.0/server.go:710 +0xa5
2021-04-08T09:21:33.456-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-04-08T09:21:33.456-0400 [DEBUG] plugin.terraform-provider-bigip_v1.8.0:    google.golang.org/grpc@v1.23.0/server.go:708 +0xa5
2021/04/08 09:21:33 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2021/04/08 09:21:33 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing

**Comment by RavinderReddyF5** [comment]
@coffmant can you share what is config you have before upgrade?

**Comment by coffmant** [comment]
Same config but bigip provider version 1.7.0

**Comment by RavinderReddyF5** [comment]
@coffmant from the error logs its noticed error is from client ssl profile tm_options settings, is it possible to share config used for clienssl profile terraform resource?

**Comment by coffmant** [comment]
[user@localhost]$ grep tm_options *tf
profileclientssl-1.tf:  tm_options    = []
profileclientssl-2.tf:  tm_options    = []
profileclientssl-3..tf:  tm_options    = []

**Comment by coffmant** [comment]
Also this may have something to do with it?

grep tm_options terraform.tfstate
            "tm_options": [],
            "tm_options": [],
            "tm_options": [],
            "tm_options": [],
            "tm_options": [],
            "tm_options": [],
            "tm_options": [],
            "tm_options": null,
            "tm_options": [],
            "tm_options": [],
            "tm_options": null,
            "tm_options": [],
            "tm_options": [],
            "tm_options": [],
            "tm_options": [],
            "tm_options": [],
            "tm_options": null,
            "tm_options": [],

**Comment by RavinderReddyF5** [comment]
@coffmant, recently we added tm_options support with v1.8.0, and verified with bigipv14,bigipv15. looks it is failing with v13.x because of response difference for GET call  between v13.x and v14.x. will work on fix and update you

**Comment by papineni87** [comment]
@coffmant  we just pushed a fix for the issue to master branch, can you clone it and verify the issue still exists ?

**Comment by coffmant** [comment]
Sorry for the delay.  I can confirm that the fix resolved this issue.  Thanks!
