### ISSUE TITLE
Plugin crashes when creating iRule

### ISSUE THREAD

**Issue by ghost** [F5Networks/terraform-provider-bigip#546]
### Environment

 * TMOS/Bigip Version: 16.1
 * Terraform Version: 1.0.3
 * Terraform bigip provider Version: 1.11.0

### Summary

Please also include information about the reproducibility and the severity/impact of the issue.

### Steps To Reproduce

1. Provide terraform resource config which you are facing trouble along with the output of it.

```console
provider "bigip" {
  username = "admin"
  password = "${var.bigipAdminPassword}"
  address = aws_eip.F5_BIGIP_AZ1EIP_MGMT.address
}
resource "bigip_ltm_irule" "aws_gwlb_health_check-inst1" {
  provider = bigip
  name = "/Common/aws_gwlb_health_check"
  irule = file("aws_gwlb_health_check.tcl")
}
```

Contents of aws_gwlb_health_check.tcl:

```tcl
when HTTP_REQUEST {
  HTTP::respond 200 OK
}

```
### Expected Behavior

I expected the iRule to be created on the device.

### Actual Behavior

The request is cancelled by Terraform because the provider crashes.

```console
bigip_ltm_irule.aws_gwlb_health_check-inst1: Creating...
aws_default_security_group.juiceShopAppSG: Modifying... [id=sg-054f9a7c8a6285465]
aws_default_security_group.juiceShopAPISG: Modifying... [id=sg-07f9462ce9f08c39b]
aws_default_security_group.juiceShopAPISG: Modifications complete after 1s [id=sg-07f9462ce9f08c39b]
aws_default_security_group.juiceShopAppSG: Modifications complete after 1s [id=sg-054f9a7c8a6285465]
╷
│ Error: Request cancelled
│ 
│   with bigip_ltm_irule.aws_gwlb_health_check-inst1,
│   on main.tf line 1096, in resource "bigip_ltm_irule" "aws_gwlb_health_check-inst1":
│ 1096: resource "bigip_ltm_irule" "aws_gwlb_health_check-inst1" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-bigip_v1.11.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x133e05e]

goroutine 49 [running]:
github.com/f5devcentral/go-bigip.(*BigIP).APICall(0x0, 0xc0005c9578, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/f5devcentral/go-bigip@v0.0.0-20210804055259-11b1d1a8dd26/bigip.go:177 +0x7e
github.com/f5devcentral/go-bigip.(*BigIP).post(0x0, 0x1b21460, 0xc0005d23c0, 0xc0005c9668, 0x2, 0x2, 0x0, 0x1b95220)
        github.com/f5devcentral/go-bigip@v0.0.0-20210804055259-11b1d1a8dd26/bigip.go:284 +0x1c5
github.com/f5devcentral/go-bigip.(*BigIP).CreateIRule(...)
        github.com/f5devcentral/go-bigip@v0.0.0-20210804055259-11b1d1a8dd26/ltm.go:2650
github.com/F5Networks/terraform-provider-bigip/bigip.resourceBigipLtmIRuleCreate(0xc0005bec40, 0x1cd1020, 0x0, 0x2, 0x24809c0)
        github.com/F5Networks/terraform-provider-bigip/bigip/resource_bigip_ltm_irule.go:56 +0x239
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000492880, 0xc0005b8960, 0xc00004e460, 0x1cd1020, 0x0, 0x1b95201, 0xc000476b78, 0xc0005b3bc0)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/resource.go:305 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0004f4600, 0xc0005c98e8, 0xc0005b8960, 0xc00004e460, 0xc000476bf0, 0xc0000a4150, 0x1b96f00)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0004881b0, 0x1e7efb0, 0xc0005b3530, 0xc0005b48a0, 0xc0004881b0, 0xc0005b3530, 0xc000102a50)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/helper/plugin/grpc_provider.go:885 +0x88b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1c8d3a0, 0xc0004881b0, 0x1e7efb0, 0xc0005b3530, 0xc0005b4840, 0x0, 0x1e7efb0, 0xc0005b3530, 0xc00020c280, 0x12b)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000c6160, 0x1e87a98, 0xc000529080, 0xc0005ca800, 0xc000469050, 0x2441a20, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:995 +0x482
google.golang.org/grpc.(*Server).handleStream(0xc0000c6160, 0x1e87a98, 0xc000529080, 0xc0005ca800, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:1275 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00048a210, 0xc0000c6160, 0x1e87a98, 0xc000529080, 0xc0005ca800)
        google.golang.org/grpc@v1.23.0/server.go:710 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.23.0/server.go:708 +0xa5

Error: The terraform-provider-bigip_v1.11.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

something bad happened
```

**Comment by trinaths** [comment]
Created INFRAANO-506 for internal tracking

**Comment by papineni87** [comment]
@grf5  I tried the same resource with same irule content , but not seeing the crash

```
HYD-ML-00064439:terraform-provider-bigip papineni$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # bigip_ltm_irule.rule2 will be created
  + resource "bigip_ltm_irule" "rule2" {
      + id    = (known after apply)
      + irule = <<~EOT
            when HTTP_REQUEST {
              HTTP::respond 200 OK
            }
        EOT
      + name  = "/Common/terraform_irule2"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

bigip_ltm_irule.rule2: Creating...
bigip_ltm_irule.rule2: Creation complete after 2s [id=/Common/terraform_irule2]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
HYD-ML-00064439:terraform-provider-bigip papineni$ 
```
```
HYD-ML-00064439:terraform-provider-bigip papineni$ terraform --version
Terraform v0.13.5
+ provider registry.terraform.io/f5networks/bigip v1.11.0

Your version of Terraform is out of date! The latest version
is 1.0.8. You can update by downloading from https://www.terraform.io/downloads.html
HYD-ML-00064439:terraform-provider-bigip papineni$ 
```

Can you try with other bigip and see if the crash is happening ?

**Comment by papineni87** [comment]
Closing the issue as it is not reproducible. Please open a new issue if you encounter it again
