### ISSUE TITLE
terraform crashing with provider as f5Networks/terraform-provider-bigip , hashicorp provided logs below

### ISSUE THREAD

**Issue by kiranjagtap41** [F5Networks/terraform-provider-bigip#574]
### Environment

 * TMOS/Bigip Version:
 * Terraform Version: 0.14.11
 * Terraform bigip provider Version: v1.11.0

### Summary

Terraform crash cause of issue with provider f5Networks/terraform-provider-bigip. 

### Steps To Reproduce
```
resource "bigip_ltm_monitor" "tcpserver-ecv" {
  name   = "/common/tcpserver-ecv"
  parent      = "/Common/tcp"
  interval      = 5
  time_until_up = 0
  timeout       = 16
  destination   = "*:22222"
  receive  = "In"
}
```
Output when running terraform apply is as below.
```
2021/11/17 21:16:20 [TRACE] statemgr.Filesystem: creating backup snapshot at terraform.tfstate.backup
2021/11/17 21:16:20 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 2
2021/11/17 21:16:20 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2021/11/17 21:16:20 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/11/17 21:16:20 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-11-17T21:16:20.120-0800 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

###################################################

Terraform  logs that Hashicorp team provided mentioning this looks to be an issue with provider.

2021-11-17T21:03:23.472-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: 2021/11/17 21:03:23 [INFO] Creating LTM Monitor /Border/stargateproxyserv_monitor_20915 :: https
2021-11-17T21:03:23.472-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: 2021/11/17 21:03:23 [INFO] Creating LTM Monitor /Border/tcpserver-ecv :: tcp
2021-11-17T21:03:23.475-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: panic: runtime error: invalid memory address or nil pointer dereference
2021-11-17T21:03:23.475-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x73e1fe]
2021-11-17T21:03:23.475-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: 
2021-11-17T21:03:23.475-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: goroutine 31 [running]:
2021-11-17T21:03:23.475-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: github.com/f5devcentral/go-bigip.(*BigIP).APICall(0x0, 0xc0001a74f0, 0x0, 0x0, 0x0, 0x0, 0x0)
2021-11-17T21:03:23.475-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0:   github.com/f5devcentral/go-bigip@v0.0.0-20210804055259-11b1d1a8dd26/bigip.go:177 +0x7e
2021-11-17T21:03:23.475-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: github.com/f5devcentral/go-bigip.(*BigIP).post(0x0, 0xfa5840, 0xc000445ba0, 0xc0001a7588, 0x3, 0x3, 0xdc1978, 0xc0003f70a0)
2021-11-17T21:03:23.475-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0:   github.com/f5devcentral/go-bigip@v0.0.0-20210804055259-11b1d1a8dd26/bigip.go:284 +0x1c5
2021-11-17T21:03:23.475-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: github.com/f5devcentral/go-bigip.(*BigIP).AddMonitor(0x0, 0xc000445ba0, 0xc000445ba0, 0xc0002f4270)
2021-11-17T21:03:23.475-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0:   github.com/f5devcentral/go-bigip@v0.0.0-20210804055259-11b1d1a8dd26/ltm.go:2571 +0x1dd
2021-11-17T21:03:23.475-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: github.com/f5devcentral/go-bigip.(*BigIP).CreateMonitor(...)
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0:   github.com/f5devcentral/go-bigip@v0.0.0-20210804055259-11b1d1a8dd26/ltm.go:2557
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: github.com/F5Networks/terraform-provider-bigip/bigip.resourceBigipLtmMonitorCreate(0xc0003f70a0, 0x10d2760, 0x0, 0x2, 0x187de80)
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0:   github.com/F5Networks/terraform-provider-bigip/bigip/resource_bigip_ltm_monitor.go:200 +0x245
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0000f9500, 0xc0003bc5a0, 0xc0002e0f20, 0x10d2760, 0x0, 0xf96901, 0xc000095c08, 0xc0005731d0)
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0:   github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/resource.go:305 +0x375
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000451100, 0xc0001a78e8, 0xc0003bc5a0, 0xc0002e0f20, 0xc000095f18, 0xc00000f198, 0xf98680)
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0:   github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/provider.go:294 +0x99
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000ebb0, 0x127fd50, 0xc00055dad0, 0xc00007bd40, 0xc00000ebb0, 0xc00055dad0, 0xc00008da50)
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0:   github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/helper/plugin/grpc_provider.go:885 +0x88b
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x108e480, 0xc00000ebb0, 0x127fd50, 0xc00055dad0, 0xc00007bce0, 0x0, 0x127fd50, 0xc00055dad0, 0xc00014a400, 0x3c1)
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0:   github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x214
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000c6000, 0x1288678, 0xc000482d80, 0xc0003e4700, 0xc0004627e0, 0x183e900, 0x0, 0x0, 0x0)
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0:   google.golang.org/grpc@v1.23.0/server.go:995 +0x482
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: google.golang.org/grpc.(*Server).handleStream(0xc0000c6000, 0x1288678, 0xc000482d80, 0xc0003e4700, 0x0)
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0:   google.golang.org/grpc@v1.23.0/server.go:1275 +0xd2c
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000370210, 0xc0000c6000, 0x1288678, 0xc000482d80, 0xc0003e4700)
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0:   google.golang.org/grpc@v1.23.0/server.go:710 +0xab
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-11-17T21:03:23.476-0800 [DEBUG] plugin.terraform-provider-bigip_v1.11.0:   google.golang.org/grpc@v1.23.0/server.go:708 +0xa5
2021-11-17T21:03:23.478-0800 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/terraform-providers/bigip/1.11.0/linux_amd64/terraform-provider-bigip_v1.11.0 pid=17002 error="exit status 2"
2021/11/17 21:03:23 [DEBUG] bigip_ltm_monitor.stargateproxyserv_monitor_20915: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Canceled desc = context canceled
```

**Comment by trinaths** [comment]
Created INFRAANO-598 for internal tracking.

**Comment by urohit011** [comment]
Hello @kiranjagtap41 , I followed the steps to reproduce the issue, but in my case terraform executed normally, without any issues. Could you please try running terraform with the latest version of the terraform-provider-bigip which is 1.12.0 as of now, and see if it is working or not?

**Comment by urohit011** [comment]
@kiranjagtap41 , we'll be closing this issue. If you face this issue again in future please open a new issue.
