### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gkor75** [F5Networks/terraform-provider-bigip#674]
### Environment

 * TMOS/Bigip Version: 16.1.x
 * HA Pair - please mind that there are two management addresses, so they cannot be defined in the 'provider' section
 * Terraform Version: v1.2.1
 * Terraform bigip provider Version: v1.15.1
 * AWS environment

### Summary

BigIP Provider crashes with `invalid memory address or nil pointer dereference`, while trying to send Declarative Onboarding.
Full message:
```
│ Error: Plugin did not respond
│ 
│   with bigip_do.bigIP_0,
│   on bigIP.tf line 197, in resource "bigip_do" "bigIP_0":
│  197: resource "bigip_do" "bigIP_0" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-bigip_v1.15.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xc57df5]

goroutine 66 [running]:
github.com/F5Networks/terraform-provider-bigip/bigip.resourceBigipDoCreate(0xe07c80?, {0xf19b20?, 0x0})
        github.com/F5Networks/terraform-provider-bigip/bigip/resource_bigip_do.go:103 +0x255
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00051b900, 0xc0000e2be0, 0xc00063c7a0, {0xf19b20, 0x0})
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/resource.go:305 +0x438
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000560980, 0xc000337818, 0xc000636e38?, 0x7?)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/provider.go:294 +0x70
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000012be8, {0xc000702a80?, 0x51f946?}, 0xc000702a80)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/helper/plugin/grpc_provider.go:885 +0x805
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xee1b20?, 0xc000012be8}, {0x10df7b0, 0xc000794150}, 0xc000702a20, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000176480, {0x10e3820, 0xc000296000}, 0xc0006ee500, 0xc00048fc50, 0x16a33a0, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:995 +0xe1e
google.golang.org/grpc.(*Server).handleStream(0xc000176480, {0x10e3820, 0xc000296000}, 0xc0006ee500, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:1275 +0xa16
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.23.0/server.go:710 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.23.0/server.go:708 +0xea

Error: The terraform-provider-bigip_v1.15.1 plugin crashed!
```

### Steps To Reproduce

1. Define a terraform code to create BigIP cluster

2. Define a terraform code to prepare Declarative Onboarding declaration for the first cluster member

3. Define BigIP provider resources to send DO:

```
provider "bigip" {
  username               = "bigipuser"
  password               = var.password
  
}

resource "bigip_do" "bigIP_0" {
  do_json               = data.template_file.DO[0].rendered
  bigip_address         = module.bigip[0].private_addresses.mgmt_private.private_ip[0]
}
```

5. `terraform apply` 

Or, set up a zoom session with g.kornacki@f5.com

### Expected Behavior

Provider doesn't crash

### Actual Behavior

Provider crashes

**Comment by KrithikaChidambaram** [comment]
Hi, thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1104, thanks!

**Comment by wojtek0806** [comment]
First attempt with the following:

```
terraform {
  required_providers {
    bigip = {
      source = "F5Networks/bigip"
      version = "1.7.0"
    }
  }
}

provider "bigip" {
  username = "xxxx"
  password = "xxxx"
}

resource "bigip_do" "do-example" {
  do_json = "${file("repro.json")}"
  bigip_address = "x.x.x.x"
  bigip_port = "xxxx"
  timeout = 5
}

```
I got an expected error:

```╷
│ Error: Error while Sending/Posting http request with DO json :<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
│ <html><head>
│ <title>401 Unauthorized</title>
│ </head><body>
│ <h1>Unauthorized</h1>
│ <p>This server could not verify that you
│ are authorized to access the document
│ requested.  Either you supplied the wrong
│ credentials (e.g., bad password), or your
│ browser doesn't understand how to supply
│ the credentials required.</p>
│ </body></html>
│   <nil>
│ 
│   with bigip_do.do-example,
│   on do.tf line 15, in resource "bigip_do" "do-example":
│   15: resource "bigip_do" "do-example" {
│ 
╵
```
If you define your target device in the resource parameter, i.e. bigip_address etc. you also need to specify bigip_user and bigip_password and other parameters releveant to your device.

I have tried the following:

```
terraform {
  required_providers {
    bigip = {
      source = "F5Networks/bigip"
      version = "1.7.0"
    }
  }
}

provider "bigip" {
  username = "xxxx"
  password = "xxxx"
}

resource "bigip_do" "do-example" {
  do_json = "${file("repro.json")}"
  bigip_address = "x.x.x.x"
  bigip_port = "xxxx"
  bigip_user = "xxxx"
  bigip_password = "xxxx"
  timeout = 5
}

And I was getting 500 error, likley due to HA setup conflicting with my declaration, in either case we tested this on:
```
Terraform v1.4.5
on darwin_amd64
+ provider registry.terraform.io/f5networks/bigip v1.7.0
```
Upgrade and retest, if problem presists, please raise a support case with reproduction env via the usual channels

**Comment by RavinderReddyF5** [comment]
hi @gkor75 please open new issue if problem is seen on latest version
