### ISSUE TITLE
Import of bigip_ltm_virtual_server crashes terraform - #2

### ISSUE THREAD

**Issue by yunal** [F5Networks/terraform-provider-bigip#764]
### Environment

 * TMOS/Bigip Version: 15.1.8
 * Terraform Version: 1.3.7
 * Terraform bigip provider Version: 1.16.2

### Summary

Encouraged by the resolution of #729 I've tested importing our whole configuration again.  And it broke.

```
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource
│ call. The plugin logs may contain more details.

Stack trace from the terraform-provider-bigip_v1.16.2 plugin:

panic: runtime error: index out of range [2] with length 0

goroutine 42 [running]:
github.com/F5Networks/terraform-provider-bigip/bigip.resourceBigipLtmVirtualServerRead(0xc0008a43f0, {0xf30c80?, 0xc0008a4b60})
        github.com/F5Networks/terraform-provider-bigip/bigip/resource_bigip_ltm_virtual_server.go:342 +0x13c5
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004c9000, 0xc00042c780, {0xf30c80, 0xc0008a4b60})
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/resource.go:455 +0x1aa
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0001308f8, {0xc00042c5a0?, 0x59d806?}, 0xc00042c5a0)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/helper/plugin/grpc_provider.go:525 +0x365
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0xef7320?, 0xc0001308f8}, {0x10fbc50, 0xc000500ba0}, 0xc000230180, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/tfplugin5/tfplugin5.pb.go:3153 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ae480, {0x10ffcc0, 0xc000562000}, 0xc0000fa900, 0xc0005018c0, 0x16c53b0, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:995 +0xe1e
google.golang.org/grpc.(*Server).handleStream(0xc0001ae480, {0x10ffcc0, 0xc000562000}, 0xc0000fa900, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:1275 +0xa16
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.23.0/server.go:710 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.23.0/server.go:708 +0xea

Error: The terraform-provider-bigip_v1.16.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps To Reproduce

I'll file a bug report with f5 with full details.

### Expected Behavior

No plugin crash.

### Actual Behavior

Plugin crash, see above.

**Comment by yunal** [comment]
F5 support ticket 00351775

**Comment by RavinderReddyF5** [comment]
Hi @yunal , is it possible to share config for reproduction of issue  through support ticket? , i could not able to reproduce the issue.

**Comment by yunal** [comment]
Hi, @RavinderReddyF5, there is a full kqview in the F5 support ticket? If you found the ticket pls email me (or call) at my work address? Thanks.

**Comment by KrithikaChidambaram** [comment]
Hi, internal ID to track this request is: INFRAANO-1082, thanks!
